// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package withresets

import (
	"context"
	"sync"
)

// Ensure, that ResetStoreMock does implement ResetStore.
// If this is not the case, regenerate this file with moq.
var _ ResetStore = &ResetStoreMock{}

// ResetStoreMock is a mock implementation of ResetStore.
//
//	func TestSomethingThatUsesResetStore(t *testing.T) {
//
//		// make and configure a mocked ResetStore
//		mockedResetStore := &ResetStoreMock{
//			ClearCacheFunc: func(id string)  {
//				panic("mock out the ClearCache method")
//			},
//			CreateFunc: func(ctx context.Context, person *Reset, confirm bool) error {
//				panic("mock out the Create method")
//			},
//			GetFunc: func(ctx context.Context, id string) (*Reset, error) {
//				panic("mock out the Get method")
//			},
//		}
//
//		// use mockedResetStore in code that requires ResetStore
//		// and then make assertions.
//
//	}
type ResetStoreMock struct {
	// ClearCacheFunc mocks the ClearCache method.
	ClearCacheFunc func(id string)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, person *Reset, confirm bool) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id string) (*Reset, error)

	// calls tracks calls to the methods.
	calls struct {
		// ResetStoreMockClearCacheCall holds details about calls to the ClearCache method.
		ClearCache []ResetStoreMockClearCacheCall
		// ResetStoreMockCreateCall holds details about calls to the Create method.
		Create []ResetStoreMockCreateCall
		// ResetStoreMockGetCall holds details about calls to the Get method.
		Get []ResetStoreMockGetCall
	}
	lockClearCache sync.RWMutex
	lockCreate     sync.RWMutex
	lockGet        sync.RWMutex
}

// ClearCache calls ClearCacheFunc.
func (mock *ResetStoreMock) ClearCache(id string) {
	if mock.ClearCacheFunc == nil {
		panic("ResetStoreMock.ClearCacheFunc: method is nil but ResetStore.ClearCache was just called")
	}
	callInfo := ResetStoreMockClearCacheCall{
		ID: id,
	}
	mock.lockClearCache.Lock()
	mock.calls.ClearCache = append(mock.calls.ClearCache, callInfo)
	mock.lockClearCache.Unlock()
	mock.ClearCacheFunc(id)
}

// ResetStoreMockClearCacheCall holds details about calls to the ClearCache method.
type ResetStoreMockClearCacheCall struct {
	// ID is the id argument value.
	ID string
}

// ClearCacheCalls gets all the calls that were made to ClearCache.
// Check the length with:
//
//	len(mockedResetStore.ClearCacheCalls())
func (mock *ResetStoreMock) ClearCacheCalls() []ResetStoreMockClearCacheCall {
	var calls []ResetStoreMockClearCacheCall
	mock.lockClearCache.RLock()
	calls = mock.calls.ClearCache
	mock.lockClearCache.RUnlock()
	return calls
}

// ResetClearCacheCalls reset all the calls that were made to ClearCache.
func (mock *ResetStoreMock) ResetClearCacheCalls() {
	mock.lockClearCache.Lock()
	mock.calls.ClearCache = nil
	mock.lockClearCache.Unlock()
}

// Create calls CreateFunc.
func (mock *ResetStoreMock) Create(ctx context.Context, person *Reset, confirm bool) error {
	if mock.CreateFunc == nil {
		panic("ResetStoreMock.CreateFunc: method is nil but ResetStore.Create was just called")
	}
	callInfo := ResetStoreMockCreateCall{
		Ctx:     ctx,
		Person:  person,
		Confirm: confirm,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, person, confirm)
}

// ResetStoreMockCreateCall holds details about calls to the Create method.
type ResetStoreMockCreateCall struct {
	// Ctx is the ctx argument value.
	Ctx context.Context
	// Person is the person argument value.
	Person *Reset
	// Confirm is the confirm argument value.
	Confirm bool
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedResetStore.CreateCalls())
func (mock *ResetStoreMock) CreateCalls() []ResetStoreMockCreateCall {
	var calls []ResetStoreMockCreateCall
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// ResetCreateCalls reset all the calls that were made to Create.
func (mock *ResetStoreMock) ResetCreateCalls() {
	mock.lockCreate.Lock()
	mock.calls.Create = nil
	mock.lockCreate.Unlock()
}

// Get calls GetFunc.
func (mock *ResetStoreMock) Get(ctx context.Context, id string) (*Reset, error) {
	if mock.GetFunc == nil {
		panic("ResetStoreMock.GetFunc: method is nil but ResetStore.Get was just called")
	}
	callInfo := ResetStoreMockGetCall{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, id)
}

// ResetStoreMockGetCall holds details about calls to the Get method.
type ResetStoreMockGetCall struct {
	// Ctx is the ctx argument value.
	Ctx context.Context
	// ID is the id argument value.
	ID string
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedResetStore.GetCalls())
func (mock *ResetStoreMock) GetCalls() []ResetStoreMockGetCall {
	var calls []ResetStoreMockGetCall
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// ResetGetCalls reset all the calls that were made to Get.
func (mock *ResetStoreMock) ResetGetCalls() {
	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *ResetStoreMock) ResetCalls() {
	mock.lockClearCache.Lock()
	mock.calls.ClearCache = nil
	mock.lockClearCache.Unlock()

	mock.lockCreate.Lock()
	mock.calls.Create = nil
	mock.lockCreate.Unlock()

	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()
}

// Ensure, that ResetStoreGenericMock does implement ResetStoreGeneric.
// If this is not the case, regenerate this file with moq.
var _ ResetStoreGeneric[any, any] = &ResetStoreGenericMock[any, any]{}

// ResetStoreGenericMock is a mock implementation of ResetStoreGeneric.
//
//	func TestSomethingThatUsesResetStoreGeneric(t *testing.T) {
//
//		// make and configure a mocked ResetStoreGeneric
//		mockedResetStoreGeneric := &ResetStoreGenericMock{
//			CreateFunc: func(ctx context.Context, id T, value S) error {
//				panic("mock out the Create method")
//			},
//			GetFunc: func(ctx context.Context, id T) (string, error) {
//				panic("mock out the Get method")
//			},
//		}
//
//		// use mockedResetStoreGeneric in code that requires ResetStoreGeneric
//		// and then make assertions.
//
//	}
type ResetStoreGenericMock[T any, S any] struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, id T, value S) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id T) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// ResetStoreGenericMockCreateCall holds details about calls to the Create method.
		Create []ResetStoreGenericMockCreateCall[T, S]
		// ResetStoreGenericMockGetCall holds details about calls to the Get method.
		Get []ResetStoreGenericMockGetCall[T, S]
	}
	lockCreate sync.RWMutex
	lockGet    sync.RWMutex
}

// Create calls CreateFunc.
func (mock *ResetStoreGenericMock[T, S]) Create(ctx context.Context, id T, value S) error {
	if mock.CreateFunc == nil {
		panic("ResetStoreGenericMock.CreateFunc: method is nil but ResetStoreGeneric.Create was just called")
	}
	callInfo := ResetStoreGenericMockCreateCall[T, S]{
		Ctx:   ctx,
		ID:    id,
		Value: value,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, id, value)
}

// ResetStoreGenericMockCreateCall holds details about calls to the Create method.
type ResetStoreGenericMockCreateCall[T any, S any] struct {
	// Ctx is the ctx argument value.
	Ctx context.Context
	// ID is the id argument value.
	ID T
	// Value is the value argument value.
	Value S
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedResetStoreGeneric.CreateCalls())
func (mock *ResetStoreGenericMock[T, S]) CreateCalls() []ResetStoreGenericMockCreateCall[T, S] {
	var calls []ResetStoreGenericMockCreateCall[T, S]
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// ResetCreateCalls reset all the calls that were made to Create.
func (mock *ResetStoreGenericMock[T, S]) ResetCreateCalls() {
	mock.lockCreate.Lock()
	mock.calls.Create = nil
	mock.lockCreate.Unlock()
}

// Get calls GetFunc.
func (mock *ResetStoreGenericMock[T, S]) Get(ctx context.Context, id T) (string, error) {
	if mock.GetFunc == nil {
		panic("ResetStoreGenericMock.GetFunc: method is nil but ResetStoreGeneric.Get was just called")
	}
	callInfo := ResetStoreGenericMockGetCall[T, S]{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, id)
}

// ResetStoreGenericMockGetCall holds details about calls to the Get method.
type ResetStoreGenericMockGetCall[T any, S any] struct {
	// Ctx is the ctx argument value.
	Ctx context.Context
	// ID is the id argument value.
	ID T
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedResetStoreGeneric.GetCalls())
func (mock *ResetStoreGenericMock[T, S]) GetCalls() []ResetStoreGenericMockGetCall[T, S] {
	var calls []ResetStoreGenericMockGetCall[T, S]
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// ResetGetCalls reset all the calls that were made to Get.
func (mock *ResetStoreGenericMock[T, S]) ResetGetCalls() {
	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *ResetStoreGenericMock[T, S]) ResetCalls() {
	mock.lockCreate.Lock()
	mock.calls.Create = nil
	mock.lockCreate.Unlock()

	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()
}
